### ISSUE TITLE
orchestrator CLI does not return GTID errant transctions

### ISSUE THREAD

**Issue by royburstein** [openark/orchestrator#1024]
Trying to find errant GTID using the CLI , can't get the errant GTID's but UI shows it . 

`# /usr/local/orchestrator/orchestrator --debug --stack -c which-gtid-errant -i my-db.mydomain.com`

2019-11-19 09:52:39 INFO starting orchestrator, version: 3.1.2, git commit: 35f46246277460331a17388bc33d326e8c58bd36
2019-11-19 09:52:39 INFO Read config: /etc/orchestrator.conf.json
2019-11-19 09:52:39 DEBUG Parsed orchestrator credentials from /etc/orchestrator_srv.cnf
2019-11-19 09:52:39 DEBUG Parsed topology credentials from /etc/orchestrator.cnf
2019-11-19 09:52:39 DEBUG Hostname unresolved yet: my-db.mydomain.com
2019-11-19 09:52:39 DEBUG Cache hostname resolve my-db.mydomain.com as my-db.mydomain.com
2019-11-19 09:52:39 DEBUG Connected to orchestrator backend: orchestrator:?@tcp(my-db.mydomain.com:3306)/orchestrator?timeout=1s
2019-11-19 09:52:39 DEBUG Orchestrator pool SetMaxOpenConns: 128
2019-11-19 09:52:39 DEBUG Initializing orchestrator
2019-11-19 09:52:39 INFO Connecting to backend my-db.mydomain.com:3306: maxConnections: 128, maxIdleConns: 32
2019-11-19 09:52:39 DEBUG Hostname unresolved yet: my-db2
2019-11-19 09:52:39 DEBUG Cache hostname resolve my-db2 as my-db2`

**Comment by shlomi-noach** [comment]
Can you please:

1. `orchestrator-client -c which-gtid-errant -i my-db.mydomain.com`

2. `select * from database_instance where hostname='my-db.mydomain.com'` (replace with real hostname)

**Comment by royburstein** [comment]
```
# orchestrator-client  -c which-gtid-errant -i my-db.mydomain.com

# echo $?
0

mysql> select * from database_instance where hostname = 'my-db.mydomain.com'\G

*************************** 1. row ***************************
                         hostname: my-db.mydomain.com
                             port: 3306
                     last_checked: 2019-11-19 12:23:31
             last_attempted_check: 2019-11-19 12:23:31
       last_check_partial_success: 1
                        last_seen: 2019-11-19 12:23:31
                           uptime: 25402646
                        server_id: 1
                      server_uuid: dc6d23d7-23b4-11e9-8e38-ecf4bbd0f020
                          version: 5.7.24-27-log
                    binlog_server: 0
                        read_only: 0
                    binlog_format: ROW
                          log_bin: 1
                log_slave_updates: 1
                  binary_log_file: mysqld-bin.002371
                   binary_log_pos: 939739822
                      master_host: 
                      master_port: 0
                slave_sql_running: 0
                 slave_io_running: 0
     replication_sql_thread_state: -1
      replication_io_thread_state: -1
          has_replication_filters: 0
                      oracle_gtid: 0
                      master_uuid: 
                    ancestry_uuid: dc6d23d7-23b4-11e9-8e38-ecf4bbd0f020
                executed_gtid_set: dc6d23d7-23b4-11e9-8e38-ecf4bbd0f020:1-3833893450
                      gtid_purged: dc6d23d7-23b4-11e9-8e38-ecf4bbd0f020:1-3694125123
                      gtid_errant: 
             supports_oracle_gtid: 1
                     mariadb_gtid: 0
                      pseudo_gtid: 0
                  master_log_file: 
              read_master_log_pos: 0
            relay_master_log_file: 
              exec_master_log_pos: 0
                   relay_log_file: 
                    relay_log_pos: 0
                   last_sql_error: 
                    last_io_error: 
            seconds_behind_master: NULL
                slave_lag_seconds: NULL
                        sql_delay: 0
                        allow_tls: 0
                  num_slave_hosts: 1
                      slave_hosts: [{"Hostname":"my-db.mydomain.com","Port":3306}]
                     cluster_name: my-db.mydomain.com:3306
          suggested_cluster_alias: My-db
                      data_center: 
                           region: 
             physical_environment: 
                   instance_alias: 
               semi_sync_enforced: 0
                replication_depth: 0
                     is_co_master: 0
replication_credentials_available: 0
      has_replication_credentials: 0
                  version_comment: Percona Server (GPL), Release 27, Revision bd42700
                    major_version: 5.7
                 binlog_row_image: FULL
           last_discovery_latency: 3696584
         semi_sync_master_enabled: 0
        semi_sync_replica_enabled: 0
                        gtid_mode: ON
```
