### ISSUE TITLE
how could i clear the old ERROR in orchestrator?

### ISSUE THREAD

**Issue by larry7xia80** [openark/orchestrator#1195]
hi @shlomi-noach ,
I  had  `Worker 1 failed executing issue`  error on orchestrator GUI after reconfigured   replication with ssl  cert .
The replication chain is

```
 (Top Master) GCP --native replication-----> mysql01( master) ---semi-sync--> mysql02(slave)
                                             |--------------------semi-sync--> mysql03(slave).
```
the error occured on mysql03(slave).  orchestrator version is 3.1.4, mysql version is  Percona server 5.7.20. 

i fixed by restart the mysql03 slave thread.
the mysql03 (slave) is up and running as below.
```
mysql> show slave status\G
*************************** 1. row ***************************
               Slave_IO_State: Waiting for master to send event
                  Master_Host: 10.#0.0.##0
                  Master_User: repl
                  Master_Port: #####
                Connect_Retry: 60
              Master_Log_File: mysql-bin.000008
          Read_Master_Log_Pos: 333198406
               Relay_Log_File: relay-bin.000009
                Relay_Log_Pos: 5864149
        Relay_Master_Log_File: mysql-bin.000008
             Slave_IO_Running: Yes
            Slave_SQL_Running: Yes
              Replicate_Do_DB: 
          Replicate_Ignore_DB: 
           Replicate_Do_Table: 
       Replicate_Ignore_Table: 
      Replicate_Wild_Do_Table: 
  Replicate_Wild_Ignore_Table: 
                   Last_Errno: 0
                   Last_Error: 
                 Skip_Counter: 0
          Exec_Master_Log_Pos: 333198406
              Relay_Log_Space: 5864350
              Until_Condition: None
               Until_Log_File: 
                Until_Log_Pos: 0
           Master_SSL_Allowed: Yes
           Master_SSL_CA_File: /####/ca.pem
           Master_SSL_CA_Path: 
              Master_SSL_Cert: /####/mysql-slave.pem
            Master_SSL_Cipher: 
               Master_SSL_Key: /####/mysql-slave.key
        Seconds_Behind_Master: 0
mysql> SELECT * from performance_schema.replication_applier_status_by_worker;
+--------------+-----------+-----------+---------------+----------------------------------------------+-------------------+--------------------+----------------------+
| CHANNEL_NAME | WORKER_ID | THREAD_ID | SERVICE_STATE | LAST_SEEN_TRANSACTION                        | LAST_ERROR_NUMBER | LAST_ERROR_MESSAGE | LAST_ERROR_TIMESTAMP |
+--------------+-----------+-----------+---------------+----------------------------------------------+-------------------+--------------------+----------------------+
|              |         1 |        58 | ON            | 3a121e8e-93b9-11ea-adec-42010a500075:2454048 |                 0 |                    | 0000-00-00 00:00:00  |
|              |         2 |        59 | ON            | 3a121e8e-93b9-11ea-adec-42010a500075:2453811 |                 0 |                    | 0000-00-00 00:00:00  |
|              |         3 |        60 | ON            | 3a121e8e-93b9-11ea-adec-42010a500075:2442188 |                 0 |                    | 0000-00-00 00:00:00  |
|              |         4 |        61 | ON            |                                              |                 0 |                    | 0000-00-00 00:00:00  |
+--------------+-----------+-----------+---------------+----------------------------------------------+-------------------+--------------------+----------------------+
```
but  orchestrator GUI still shows the error. 
how could i clear the ERROR in orchestrator? 
i tried to click the skip query, but no luck ,shows bad connection/command etc.

thanks 
Best Regards,
Larry
