### ISSUE TITLE
Integrate the orchestrator and a cluster managed by Vitess

### ISSUE THREAD

**Issue by pparshin** [openark/orchestrator#1379]
Hi,

I read the documentation how to config the orchestrator to monitor the Vitess cluster. it seems straight forward, but I also have clusters not managed by Vitess and my current config conflicts with the suggested one:

```yaml
  "DetectClusterAliasQuery": "select ifnull(max(cluster_name), '') as cluster_alias from meta.cluster where anchor=1",
  "DetectClusterDomainQuery": "select ifnull(max(cluster_domain), '') as cluster_domain from meta.cluster where anchor=1",
  "DetectInstanceAliasQuery": "",
  "DetectPromotionRuleQuery": "",
```

Is it possible to config the orchestrator to monitor sharded and not-sharded clusters or should I set up a different orchestrator instance only for Vitess clusters?
