### ISSUE TITLE
want to add raft support for SetClusterAliasManualOverride

### ISSUE THREAD

**Issue by MOON-CLJ** [openark/orchestrator#775]
we use orchestrator/raft high availability mode for orchestrator itself，

and we use api set-cluster-alias/:clusterName to register cluster_alias to orchestrator instead of DetectClusterAliasQuery to avoid create a meta.cluster 。

but SetClusterAliasManualOverride only write to the leader，because of the limit of isAuthorizedForAction，we also cant reach the followers。

followers don't have the info in table cluster_alias_override，cause some problem。such as，the ack-recovery command sync from leader apply on followers doesn't update table topology_recovery。

the leader backend's data

```
              acknowledged: 1
           acknowledged_at: 2019-01-15 13:28:04
           acknowledged_by: orc
       acknowledge_comment: auto ack for graceful-master-takeover
         last_detection_id: 1314
           successor_alias: dba-mysql-orchtest08
                       uid: 1547530071024212480:88da89bb9003a4c97c96da6d2f28a13ba3c58ca21736859c8b753ea9806f1a6d
1 row in set (0.00 sec)

orchestrator_server@orchestrator01:31:01>select * from  topology_recovery where  uid="1547530071024212480:88da89bb9003a4c97c96da6d2f28a13ba3c58ca21736859c8b753ea9806f1a6d"\G
```

the follower backend's data

```
              acknowledged: 0
           acknowledged_at: NULL
           acknowledged_by:
       acknowledge_comment:
         last_detection_id: 987207
           successor_alias: dba-mysql-orchtest08
                       uid: 1547530071024212480:88da89bb9003a4c97c96da6d2f28a13ba3c58ca21736859c8b753ea9806f1a6d
1 row in set (0.00 sec)

orchestrator_server@orchestrator01:32:52>select * from  topology_recovery where  uid="1547530071024212480:88da89bb9003a4c97c96da6d2f28a13ba3c58ca21736859c8b753ea9806f1a6d"\G
```

the reason is comment in following code。

```
func AcknowledgeClusterRecoveries(clusterName string, owner string, comment string) (countAcknowledgedEntries int64, err error) {
         **// because of topology_recovery's cluster_name is old master's host:port，but clusterName is new master's host:port，so the `cluster_name = ?` cant match in leader and followers。**
	{
		whereClause := `cluster_name = ?`
		args := sqlutils.Args(clusterName)
		clearAcknowledgedFailureDetections(whereClause, args)
		count, err := acknowledgeRecoveries(owner, comment, false, whereClause, args)
		if err != nil {
			return count, err
		}
		countAcknowledgedEntries = countAcknowledgedEntries + count
	}
        **// in leader because of inst.ReadClusterInfo(clusterName) and database_instance and cluster_alias both have alias info，so clusterInfo.ClusterAlias can have the right value。
        // but in followers，because of database_instance and cluster_alias don't have alias info, clusterInfo.ClusterAlias cant have the right value，so the update have no affected rows。**
	{
		clusterInfo, err := inst.ReadClusterInfo(clusterName)
		whereClause := `cluster_alias = ? and cluster_alias != ''`
		args := sqlutils.Args(clusterInfo.ClusterAlias)
		clearAcknowledgedFailureDetections(whereClause, args)
		count, err := acknowledgeRecoveries(owner, comment, false, whereClause, args)
		if err != nil {
			return count, err
		}
		countAcknowledgedEntries = countAcknowledgedEntries + count

	}
	return countAcknowledgedEntries, nil
}
```

cc @yangeagle
