### ISSUE TITLE
in clusters->dashboard page, instance_problems list can't scroll with page.

### ISSUE THREAD

**Issue by martianzhang** [openark/orchestrator#835]
## Problem

`resources/public/css/orchestrator.css`

```css
 #instance_problems {
     z-index: 10;
     position: fixed;
     right: 0px;
     padding-right: 15px;
 }
```

`instance_problems` button's position was fixed, when there are many instances with problem, list can't scroll with page. So we can't see all the problems except  using api.

## Suggest

`resources/public/css/orchestrator.css`

```css
 #instance_problems {
     z-index: 10;
     right: 0px;
     padding-right: 15px;
 }
```
or move this button to the title bar.
