### ISSUE TITLE
Relocating 1 replicas turns to be too complex

### ISSUE THREAD

**Issue by NielsH** [openark/orchestrator#876]
Hi,

I'm trying out Orchestrator and running into some issues
First let me explain the setup:
Running Debian 9 with MariaDB 10.2
3 nodes with WAN + LAN IPs. 
1 node is master, 2 slaves directly from the master
MySQL is running on port 3307
Slaving happens over the LAN interface. Directly configured by IP, so not hostnames.

Server hostnames:  
sqlproxytest01 (master - 172.29.176.80)
sqlproxytest02 (slave of master - 172.29.176.81)
sqlproxytest03 (slave of master - 172.29.176.82)

I installed Orchestrator with Raft/sqlite on the 3 nodes as well. 

Changed settings from defaults, excluding login credentials for the Orchestrator config:
```
  "RaftEnabled": true,
  "RaftDataDir": "/usr/local/orchestrator",
  "RaftBind": "172.29.176.80",
  "DefaultRaftPort": 10008,
  "RaftNodes": ["172.29.176.80", "172.29.176.81", "172.29.176.82"],
  "MySQLConnectTimeoutSeconds": 1,
  "DefaultInstancePort": 3307,
  "DiscoverByShowSlaveHosts": true,
  "HostnameResolveMethod": "",
  "MySQLHostnameResolveMethod": "@@report_host",
```

I configured the my.cnf with these options:`
Of course I also changed the IP on each node to reflect its own IP
```
[mysqld]
report_host=172.29.176.80
report_port=3307

binlog_format=ROW
innodb_autoinc_lock_mode=2
innodb_doublewrite=1
innodb_log_file_size=512M
innodb_flush_log_at_trx_commit=0
enforce_storage_engine=innodb
sql_mode="NO_AUTO_CREATE_USER"

# Replication specific
[mariadb]
log-bin
server_id=1
log-basename=master1
max_binlog_size=1G
expire_logs_days=7
relay-log-recovery=1
slave-type-conversions=ALL_NON_LOSSY
slave_parallel_threads=8
slave_parallel_mode=optimistic
# only on slaves, commented out on master
read_only=1
```

Now I try to do a master takeover:
```
root@sqlproxytest01:~# orchestrator-client -c graceful-master-takeover -i sqlproxytest01 -d 172.29.176.81:3307
Desginated instance 172.29.176.81:3307 cannot take over all of its siblings. Error: 2019-05-07 20:52:49 ERROR Relocating 1 replicas of 172.29.176.80:3307 below 172.29.176.81:3307 turns to be too complex; please do it manually

root@sqlproxytest01:~# orchestrator-client -c topology -alias sqlproxytest01
172.29.176.80:3307   [0s,ok,10.2.23-MariaDB-10.2.23+maria~stretch-log,rw,ROW]
+ 172.29.176.81:3307 [0s,ok,10.2.23-MariaDB-10.2.23+maria~stretch-log,ro,ROW,GTID]
+ 172.29.176.82:3307 [0s,ok,10.2.23-MariaDB-10.2.23+maria~stretch-log,ro,ROW,GTID]
```

Is this type of replication not supported? What do I need to change here?

Cheers!

**Comment by shlomi-noach** [comment]
In this setup:
```
172.29.176.80:3307   [0s,ok,10.2.23-MariaDB-10.2.23+maria~stretch-log,rw,ROW]
+ 172.29.176.81:3307 [0s,ok,10.2.23-MariaDB-10.2.23+maria~stretch-log,ro,ROW,GTID]
+ 172.29.176.82:3307 [0s,ok,10.2.23-MariaDB-10.2.23+maria~stretch-log,ro,ROW,GTID]
```
Can you try `orchestrator-client -c relocate -i 172.29.176.82:3307 -d 172.29.176.81:3307` ?
Can you run `orchestrator` with `--debug --stack` and paste the log from that operation?

**Comment by shlomi-noach** [comment]
Also, please paste `show slave status\G` for both `81` and `82` servers.

**Comment by NielsH** [comment]
Hi,

Here is the show slave status:
81 server (sqlproxytest02)
```
*************************** 1. row ***************************
               Slave_IO_State: Waiting for master to send event
                  Master_Host: 172.29.176.80
                  Master_User: replication
                  Master_Port: 3307
                Connect_Retry: 10
              Master_Log_File: master1-bin.000008
          Read_Master_Log_Pos: 488
               Relay_Log_File: master1-relay-bin.000002
                Relay_Log_Pos: 688
        Relay_Master_Log_File: master1-bin.000008
             Slave_IO_Running: Yes
            Slave_SQL_Running: Yes
              Replicate_Do_DB:
          Replicate_Ignore_DB:
           Replicate_Do_Table:
       Replicate_Ignore_Table:
      Replicate_Wild_Do_Table:
  Replicate_Wild_Ignore_Table:
                   Last_Errno: 0
                   Last_Error:
                 Skip_Counter: 0
          Exec_Master_Log_Pos: 488
              Relay_Log_Space: 999
              Until_Condition: None
               Until_Log_File:
                Until_Log_Pos: 0
           Master_SSL_Allowed: No
           Master_SSL_CA_File:
           Master_SSL_CA_Path:
              Master_SSL_Cert:
            Master_SSL_Cipher:
               Master_SSL_Key:
        Seconds_Behind_Master: 0
Master_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 0
                Last_IO_Error:
               Last_SQL_Errno: 0
               Last_SQL_Error:
  Replicate_Ignore_Server_Ids:
             Master_Server_Id: 1
               Master_SSL_Crl:
           Master_SSL_Crlpath:
                   Using_Gtid: Slave_Pos
                  Gtid_IO_Pos: 0-1-17
      Replicate_Do_Domain_Ids:
  Replicate_Ignore_Domain_Ids:
                Parallel_Mode: optimistic
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
      Slave_SQL_Running_State: Slave has read all relay log; waiting for the slave I/O thread to update it
```

82 server (sqlproxytest03)
```
*************************** 1. row ***************************
               Slave_IO_State: Waiting for master to send event
                  Master_Host: 172.29.176.80
                  Master_User: replication
                  Master_Port: 3307
                Connect_Retry: 10
              Master_Log_File: master1-bin.000008
          Read_Master_Log_Pos: 488
               Relay_Log_File: master1-relay-bin.000002
                Relay_Log_Pos: 789
        Relay_Master_Log_File: master1-bin.000008
             Slave_IO_Running: Yes
            Slave_SQL_Running: Yes
              Replicate_Do_DB:
          Replicate_Ignore_DB:
           Replicate_Do_Table:
       Replicate_Ignore_Table:
      Replicate_Wild_Do_Table:
  Replicate_Wild_Ignore_Table:
                   Last_Errno: 0
                   Last_Error:
                 Skip_Counter: 0
          Exec_Master_Log_Pos: 488
              Relay_Log_Space: 1100
              Until_Condition: None
               Until_Log_File:
                Until_Log_Pos: 0
           Master_SSL_Allowed: No
           Master_SSL_CA_File:
           Master_SSL_CA_Path:
              Master_SSL_Cert:
            Master_SSL_Cipher:
               Master_SSL_Key:
        Seconds_Behind_Master: 0
Master_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 0
                Last_IO_Error:
               Last_SQL_Errno: 0
               Last_SQL_Error:
  Replicate_Ignore_Server_Ids:
             Master_Server_Id: 1
               Master_SSL_Crl:
           Master_SSL_Crlpath:
                   Using_Gtid: Slave_Pos
                  Gtid_IO_Pos: 0-1-17
      Replicate_Do_Domain_Ids:
  Replicate_Ignore_Domain_Ids:
                Parallel_Mode: optimistic
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
      Slave_SQL_Running_State: Slave has read all relay log; waiting for the slave I/O thread to update it
```

If I run the relocate command I get:
```
orchestrator-client -c relocate -i 172.29.176.82:3307 -d 172.29.176.81:3307
2019-05-08 09:15:29 ERROR 172.29.176.82:3307 cannot replicate from 172.29.176.81:3307. Reason: instance does not have log_slave_updates enabled: 172.29.176.81:3307
```
```
[martini] Started GET /api/relocate/172.29.176.82/3307/172.29.176.81/3307 for 172.29.176.80:56558
2019-05-08 09:25:30 ERROR 172.29.176.82:3307 cannot replicate from 172.29.176.81:3307. Reason: instance does not have log_slave_updates enabled: 172.29.176.81:3307
[martini] Completed 500 Internal Server Error in 2.425354ms
2019-05-08 09:25:31 DEBUG raft leader is 172.29.176.80:10008 (this host); state: Leader

```
I'd guess this is expected as what I think the command does is make 172.29.176.82 a slave of 172.29.176.81? I thought that only if you want to chain the replication (which I guess this does) you need to have `log_slave_updates`, but in my case I have 1 master and 2 nodes slaving from that master.

fwiw this is what I get for the graceful-master-takeover in the log:
```
[martini] Started GET /api/graceful-master-takeover/sqlproxytest01/172.29.176.81/3307 for 172.29.176.80:56566
2019-05-08 09:26:07 INFO GracefulMasterTakeover: designated master instructed to be 172.29.176.81:3307
2019-05-08 09:26:07 INFO GracefulMasterTakeover: Will let 172.29.176.81:3307 take over its siblings
2019-05-08 09:26:07 INFO moveReplicasViaGTID: Will move 1 replicas below 172.29.176.81:3307 via GTID
2019-05-08 09:26:07 ERROR Relocating 1 replicas of 172.29.176.80:3307 below 172.29.176.81:3307 turns to be too complex; please do it manually
[martini] Completed 500 Internal Server Error in 15.317194ms

```
