### ISSUE TITLE
Enabling GTID on exsiting MySQL slave breaks the replication

### ISSUE THREAD

**Issue by TheSuperAgent** [openark/orchestrator#879]
* MySQL version 5.6
* Orchestrator version: 3.0.13

### On Master node:
```
create database rep_test;
use rep_test;
create table num(id int);
insert into num values (1);
```
 
## Take dump:
```
mysqldump -uroot -p --set-gtid-purged=OFF  --database rep_test > rep_test.sql
```

## Restore the DB on Slave:
```
[Cleanup the slave]
stop slave;
reset slave all;
reset master;
[restore]
mysql -uroot -p <  rep_test.sql
```

## Get binlog info from dump:

```
less rep_test.sql
-- CHANGE MASTER TO MASTER_LOG_FILE='mysqld-bin.000001', MASTER_LOG_POS=704;
```
## Establish the replication:
```
CHANGE MASTER TO MASTER_HOST='10.142.0.25',MASTER_USER='bhuvi', MASTER_PASSWORD='bhuvi', MASTER_LOG_FILE='mysqld-bin.000001', MASTER_LOG_POS= 704;
start slave;
show slave stauts\G
   Slave_IO_State: Waiting for master to send event
                  Master_Host: 10.142.0.25
                  Master_User: bhuvi
                  Master_Port: 3306
                Connect_Retry: 60
              Master_Log_File: mysqld-bin.000001
          Read_Master_Log_Pos: 949
               Relay_Log_File: mysqld-relay-bin.000002
                Relay_Log_Pos: 560
        Relay_Master_Log_File: mysqld-bin.000001
             Slave_IO_Running: Yes
            Slave_SQL_Running: Yes
......
......
   SQL_Remaining_Delay: NULL
      Slave_SQL_Running_State: Slave has read all relay log; waiting for the slave I/O thread to update it
           Master_Retry_Count: 86400
                  Master_Bind: 
      Last_IO_Error_Timestamp: 
     Last_SQL_Error_Timestamp: 
               Master_SSL_Crl: 
           Master_SSL_Crlpath: 
           Retrieved_Gtid_Set: 5532ce2e-71bb-11e9-887c-42010a8e0019:4
            Executed_Gtid_Set: 5532ce2e-71bb-11e9-887c-42010a8e0019:4,
9da3e2f6-71b8-11e9-886a-42010a8e0013:1-6
                Auto_Position: 0
```

## Test the replication:
```
Master> insert into num values (2);
slave> select * from rep_test.num;
+------+
| id   |
+------+
|    1 |
|    2 |
+------+
```

## Enable GTID from Orchestrator UI:
Before doing this, I saw it had some errant transactions. So I did reset master from the UI.
![errant](https://user-images.githubusercontent.com/47310439/57406835-5f3dde00-71ff-11e9-8d46-a19869e5921a.png)

Then I clicked the ENABLE button for enabling GTID based replication.

## Replication Broke:
```
Slave> show slave status\G
*************************** 1. row ***************************
               Slave_IO_State: Waiting for master to send event
                  Master_Host: bhuvi-1
                  Master_User: bhuvi
                  Master_Port: 3306
                Connect_Retry: 60
              Master_Log_File: mysqld-bin.000001
          Read_Master_Log_Pos: 949
               Relay_Log_File: mysqld-relay-bin.000002
                Relay_Log_Pos: 363
        Relay_Master_Log_File: mysqld-bin.000001
             Slave_IO_Running: Yes
            Slave_SQL_Running: No
              Replicate_Do_DB: 
          Replicate_Ignore_DB: 
           Replicate_Do_Table: 
       Replicate_Ignore_Table: 
      Replicate_Wild_Do_Table: 
  Replicate_Wild_Ignore_Table: 
                   Last_Errno: 1007
Last_Error: Error 'Can't create database 'rep_test'; database exists' on query. Default database: 'rep_test'. Query: 'create database rep_test'
                 Skip_Counter: 0
          Exec_Master_Log_Pos: 151
              Relay_Log_Space: 1169
              Until_Condition: None
               Until_Log_File: 
                Until_Log_Pos: 0
           Master_SSL_Allowed: No
           Master_SSL_CA_File: 
           Master_SSL_CA_Path: 
              Master_SSL_Cert: 
            Master_SSL_Cipher: 
               Master_SSL_Key: 
        Seconds_Behind_Master: NULL
Master_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 0
                Last_IO_Error: 
               Last_SQL_Errno: 1007
               Last_SQL_Error: Error 'Can't create database 'rep_test'; database exists' on query. Default database: 'rep_test'. Query: 'create database rep_test'
  Replicate_Ignore_Server_Ids: 
             Master_Server_Id: 1
                  Master_UUID: 5532ce2e-71bb-11e9-887c-42010a8e0019
             Master_Info_File: /var/lib/mysql/master.info
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
      Slave_SQL_Running_State: 
           Master_Retry_Count: 86400
                  Master_Bind: 
      Last_IO_Error_Timestamp: 
     Last_SQL_Error_Timestamp: 190508 20:28:54
               Master_SSL_Crl: 
           Master_SSL_Crlpath: 
           Retrieved_Gtid_Set: 5532ce2e-71bb-11e9-887c-42010a8e0019:1-3
            Executed_Gtid_Set: 5532ce2e-71bb-11e9-887c-42010a8e0019:4
                Auto_Position: 1
```
